version: '3.9'
services:
  postgres_db:
    container_name: michoacana_db
    image: postgres:15.8
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=michoacana